# Generated by Django 3.2.16 on 2023-02-28 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_costumer_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('bihar', 'bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chhattisgarh', 'Chhattisgarh')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
